version: "3"
services:
  app:
    container_name: api
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@localhost:5432/test
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql@16/data
    restart: always

volumes:
  db-data:
    driver: local
